name: 'DriftControl'
description: 'Detects and analyzes API and database drift in pull requests'
author: 'driftcontrol'
branding:
  icon: 'git-branch'
  color: 'blue'

inputs:
  token:
    description: 'GitHub token for API access (defaults to GITHUB_TOKEN)'
    required: false
    default: ${{ github.token }}
  openapi_path:
    description: 'Path to the OpenAPI spec file'
    required: false
    default: 'openapi.yaml'
  sql_glob:
    description: 'Glob pattern for SQL migration files'
    required: false
    default: 'migrations/**/*.sql'
  fail_on_medium:
    description: 'Boolean to fail the check on medium-severity drift'
    required: false
    default: 'false'
  override:
    description: 'Boolean to bypass the merge block'
    required: false
    default: 'false'

runs:
  using: 'node20'
  main: 'src/index.js'