name: 'DriftControl'
description: 'Detects and analyzes API and database drift in pull requests'
author: 'driftcontrol'
branding:
  icon: 'git-branch'
  color: 'blue'

inputs:
  token:
    description: 'GitHub token for API access (defaults to GITHUB_TOKEN)'
    required: false
    default: ${{ github.token }}
  openapi_path:
    description: 'Path to the OpenAPI spec file (can be configured in .github/driftcontrol.yml)'
    required: false
    default: 'openapi.yaml'
  sql_glob:
    description: 'Glob pattern for SQL migration files (can be configured in .github/driftcontrol.yml)'
    required: false
    default: 'migrations/**/*.sql'
  fail_on_medium:
    description: 'Boolean to fail the check on medium-severity drift (can be configured in .github/driftcontrol.yml)'
    required: false
    default: 'false'
  override:
    description: 'Boolean to bypass the merge block (can be configured in .github/driftcontrol.yml)'
    required: false
    default: 'false'
  terraform_plan_path:
    description: 'Path to Terraform plan JSON file (can be configured in .github/driftcontrol.yml)'
    required: false
    default: ''
  cloudformation_glob:
    description: 'Glob pattern for CloudFormation template files (can be configured in .github/driftcontrol.yml)'
    required: false
    default: ''
  cost_threshold:
    description: 'Cost increase threshold in USD to trigger medium severity (can be configured in .github/driftcontrol.yml)'
    required: false
    default: '1000'
  config_yaml_glob:
    description: 'Glob pattern for configuration YAML files (can be configured in .github/driftcontrol.yml)'
    required: false
    default: ''
  feature_flags_path:
    description: 'Path to feature flags configuration file (can be configured in .github/driftcontrol.yml)'
    required: false
    default: ''
  correlation_config_path:
    description: 'Path to DriftControl configuration file for centralized settings and correlation rules'
    required: false
    default: '.github/driftcontrol.yml'
  vulnerability_provider:
    description: 'Vulnerability detection provider - static, github (can be configured in .github/driftcontrol.yml)'
    required: false
    default: 'static'
  kubernetes_glob:
    description: 'Glob pattern for Kubernetes manifest files (can be configured in .github/driftcontrol.yml)'
    required: false
    default: '**/k8s/**/*.{yaml,yml}'
  env_files:
    description: 'Analyze .env files for secret changes (can be configured in .github/driftcontrol.yml)'
    required: false
    default: 'true'
  llm_provider:
    description: 'LLM provider for enhanced explanations - openai or anthropic (can be configured in .github/driftcontrol.yml)'
    required: false
    default: ''
  llm_api_key:
    description: 'API key for LLM provider (use GitHub secrets) - centralized config recommended'
    required: false
    default: ''
  llm_model:
    description: 'Model to use - gpt-4, gpt-3.5-turbo, claude-3-opus, claude-3-sonnet (can be configured in .github/driftcontrol.yml)'
    required: false
    default: ''
  llm_max_tokens:
    description: 'Maximum tokens for LLM response (can be configured in .github/driftcontrol.yml)'
    required: false
    default: '150'

runs:
  using: 'node20'
  main: 'dist/index.js'